apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/data/ghost
    server: nfs.anderson.local
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status: {}
