apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: ghost-deploy
  namespace: default
spec:
  ports:
  - name: web
    port: 2368
    protocol: TCP
    targetPort: 2368
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-ghost-deploy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
