apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: rilieghost-deploy
  namespace: default
spec:
  clusterIP: 10.43.121.99
  clusterIPs:
  - 10.43.121.99
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 2368
    protocol: TCP
    targetPort: 2368
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-rilieghost-deploy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
